name: FileHound
options:
  deploymentTarget:
    macOS: "11.0"
  swiftVersion: "5.10"
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.1
  MMKV:
    url: https://github.com/Tencent/MMKV
    from: 2.2.4
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.8.1
settings:
  base:
    SWIFT_VERSION: "5.10"
targets:
  FileHound:
    type: application
    platform: macOS
    sources:
      - FileHound
    dependencies:
      - package: SnapKit
      - package: MMKV
      - package: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHound
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.10"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) SPARKLE_ENABLED"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleShortVersionString: "$(MARKETING_VERSION)"
        INFOPLIST_KEY_CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        CODE_SIGN_ENTITLEMENTS: FileHound/FileHound.entitlements
      configs:
        Debug:
          SWIFT_VERSION: "5.10"
        Release:
          SWIFT_VERSION: "5.10"
  FileHoundHelper:
    type: tool
    platform: macOS
    sources:
      - FileHoundHelper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHoundHelper
        SWIFT_VERSION: "5.10"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_ENTITLEMENTS: FileHoundHelper/FileHoundHelper.entitlements
      configs:
        Debug:
          SWIFT_VERSION: "5.10"
        Release:
          SWIFT_VERSION: "5.10"
  FileHoundTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - FileHoundTests
    dependencies:
      - target: FileHound
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHoundTests
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          SWIFT_VERSION: "5.10"
        Release:
          SWIFT_VERSION: "5.10"
  FileHoundUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - FileHoundUITests
    dependencies:
      - target: FileHound
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHoundUITests
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          SWIFT_VERSION: "5.10"
        Release:
          SWIFT_VERSION: "5.10"
