name: FileHound
options:
  deploymentTarget:
    macOS: "11.0"
targets:
  FileHound:
    type: application
    platform: macOS
    sources:
      - FileHound
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHound
        SWIFT_VERSION: 5.10
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
  FileHoundTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - FileHoundTests
    dependencies:
      - target: FileHound
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHoundTests
        GENERATE_INFOPLIST_FILE: YES
  FileHoundUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - FileHoundUITests
    dependencies:
      - target: FileHound
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.vanjay.FileHoundUITests
        GENERATE_INFOPLIST_FILE: YES
